## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

## Switches
set_property PACKAGE_PIN V17 [get_ports {sw_1}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_1}]
set_property PACKAGE_PIN V16 [get_ports {sw_2}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_2}]
set_property PACKAGE_PIN W16 [get_ports {sw_5}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_5}]
set_property PACKAGE_PIN W17 [get_ports {sw_10}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_10}]
set_property PACKAGE_PIN W13 [get_ports {reset}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN R3 [get_ports {sw_select[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_select[0]}]
set_property PACKAGE_PIN W2 [get_ports {sw_select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_select[1]}]
set_property PACKAGE_PIN U1 [get_ports {sw_select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_select[2]}]
set_property PACKAGE_PIN T1 [get_ports {sw_select[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_select[3]}]
set_property PACKAGE_PIN R2 [get_ports {sw_select[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_select[4]}]

## 7 Segment display
set_property PACKAGE_PIN W7 [get_ports {seg_display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg_display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg_display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg_display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg_display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg_display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg_display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_display[6]}]

set_property PACKAGE_PIN U2 [get_ports {anode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]

## Buttons
set_property PACKAGE_PIN U18 [get_ports confirm_btn]
set_property IOSTANDARD LVCMOS33 [get_ports confirm_btn]
